minimum_pre_commit_version: 2.9.0

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: 'https://github.com/psf/black'
    rev: 20.8b1
    hooks:
      - id: black
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-builtin-literals
      # TODO: check-json is emitting clear false positives
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
