name: Check Markdown links

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
      - master
      - main

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
