# Build, test, and publish to releases, packages, PyPi, etc.
# Runs when creating a Github release
name: Publish on release creation
on:
  release:
    types: [published]
  repository_dispatch:
    types: [release-made]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: read action options
        id: read_options
        run: |
          json=`cat .github/action-options.json`
          USE_SLACK=`echo $(jq -r '.use_slack' <<< "$json")`
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install build meta-dependencies
        run: |
          pip install poetry tox
      - name: Test with tox
        run: |
          tox -v
      - name: Build sdists and wheels with Poetry
        run: |
          poetry build
          poetry install
      - name: Build the Docker image
        run: |
          docker build .
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/${{ github.event.repository.name }}
          tag_with_ref: true
      - name: Attach artifacts to the Github release
        uses: skx/github-action-publish-binaries@master
        with:
          args: "dist/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to PyPi
        run: |
          poetry publish -vv --username __token__ --password ${{ secrets.PYPI_TOKEN }}
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,action,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always() && steps.read_options.outputs.USE_SLACK=='true'
