# SPDX-FileCopyrightText: Copyright 2020-2023, Contributors to pocketutils
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/pocketutils
# SPDX-License-Identifier: Apache-2.0

name: Push

on:
  push:
    branches:
      - main
      - "releases/**"

permissions:
  contents: write
  statuses: write
  actions: write
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    uses: ./.github/workflows/_test.yaml
    secrets: inherit

  send-coverage:
    name: Update coveralls and codecov
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        # :tyranno: python: ${tool.hatch.envs.all.matrix.python~[0]~}
        python: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download coverage artifact for ${{ matrix.os }}/${{ matrix.python }}
        uses: actions/download-artifact@v3
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python }}
      - name: Send ${{ matrix.os }}/${{ matrix.python }} to coveralls
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-${{ join(matrix.*, '-') }}
          parallel: true
      - name: Send ${{ matrix.os }}/${{ matrix.python }} to codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: matrix.os,matrix.python
          fail_ci_if_error: true
    needs: [test]

  finish:
    needs: [send-coverage]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send final data to coveralls
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          file: coverage.xml

  make-changelog:
    runs-on: ubuntu-latest
    needs: [send-coverage]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: |
          pip install commitizen
          cz changelog
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: auto-generate changelog"
          file_pattern: CHANGELOG.md
